openapi: 3.0.0
info:
  title: 'SwaggerLume OpenApi'
  description: 'SwaggerLume OpenApi description'
  contact:
    email: darius@matulionis.lt
  license:
    name: 'Apache 2.0'
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.0
servers:
  -
    url: 'http://my-default-host.com'
    description: 'SwaggerLume OpenApi dynamic host server'
  -
    url: 'https://projects.dev/api/v1'
    description: 'SwaggerLume OpenApi Server'
paths:
  /projects:
    get:
      tags:
        - Projects
      summary: 'Get list of projects'
      description: 'Returns list of projects'
      operationId: getProjectsList
      responses:
        200:
          description: 'successful operation'
        400:
          description: 'Bad request'
      security:
        -
          api_key_security_example: []
  '/projects/{id}':
    get:
      tags:
        - Projects
      summary: 'Get project information'
      description: 'Returns project data'
      operationId: getProjectById
      parameters:
        -
          name: id
          in: path
          description: 'Project id'
          required: true
          schema:
            type: integer
      responses:
        200:
          description: 'successful operation'
        400:
          description: 'Bad request'
        404:
          description: 'Resource Not Found'
      security:
        -
          oauth2_security_example:
            - 'write:projects'
            - 'read:projects'
components:
  securitySchemes:
    'Password Based':
      type: oauth2
      description: 'Use a global client_id / client_secret and your username / password combo to obtain a token'
      in: header
      flows:
        password:
          authorizationUrl: /oauth/authorize
          tokenUrl: /oauth/token
          refreshUrl: /oauth/token/refresh
          scopes: []
      scheme: https
tags:
  -
    name: project
    description: 'Everything about your Projects'
    externalDocs:
      description: 'Find out more'
      url: 'http://swagger.io'
  -
    name: user
    description: 'Operations about user'
    externalDocs:
      description: 'Find out more about'
      url: 'http://swagger.io'
externalDocs:
  description: 'Find out more about Swagger'
  url: 'http://swagger.io'
